import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "KLTL Studios",
  description: "Generated by create next app",
  icons: {
    icon: "/icon/KLTL_Studios.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="main-header">
          <Image
            src="/icon/Icon.svg"
            width={160}
            height={100}
            alt="KLTL Studios Logo"
            className="logo"
          />
          <nav className="header-nav">
            <Link href="/" className="default-btn">
              <h1>Home</h1>
            </Link>
            <Link href="/about" className="default-btn">
              <h1>About</h1>
            </Link>
            <Link href="/projects" className="default-btn">
              <h1>My Projects</h1>
            </Link>
          </nav>
        </header>

        {children}

        <footer className="nav-bottom">
          <div className="nav-bottom-left">
            <h2> &copy; 2025 KLTL Studios.</h2>
          </div>
          {/* <div className="nav-bottom-right">
            <a href="#">Privacy</a> | <a href="#">Terms</a>
          </div> */}
        </footer>
      </body>
    </html>
  );
}
